---
- name: Create new Active-Directory Domain & Forest | https://madlabber.wordpress.com/2019/09/08/creating-a-new-active-directory-forest-with-ansible/
  hosts: dc1
  vars:
    domain_name: "demo.lab"
    recovery_password: 'W3lcome$1'
    reverse_dns_zone: "192.168.142.0/24"

  gather_facts: no
  tasks:
  

  - name: Install Active Directory
    win_feature: >
         name=AD-Domain-Services
         include_management_tools=yes
         include_sub_features=yes
         state=present
    register: result

  - name: Create Domain
    win_domain: >
       dns_domain_name='{{ domain_name }}'
       safe_mode_password='{{ recovery_password }}'
    register: ad
    
  - name: reboot server
    win_reboot:
     msg: "Installing AD. Rebooting..."
     pre_reboot_delay: 15
    when: ad.changed
    
  - name: Set internal DNS server 
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '127.0.0.1'
  
  - name: Create reverse DNS zone
    win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"  
    retries: 2
    delay: 10
    register: result           
    until: result is succeeded
