---
- name: Disable ipv6 via registry key
  hosts: all
  gather_facts: no

  tasks:
    - name: adding reg key 
      ansible.windows.win_regedit:
        path: 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
        name: 'DisabledComponents'
        data: '0xff'
        type: dword
        state: present
      register: done

    - name: reboot server
      win_reboot:
        msg: "Installing AD. Rebooting..."
        pre_reboot_delay: 15
      when: done.changed