---
- name: Disable ipv6 via registry key
  hosts: all
  gather_facts: no

  tasks:
    - name: adding reg key
      ansible.windows.win_regedit:
        key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
        value: DisabledComponents
        data: 0xff
        datatype: dword
        state: present
      register: complete
    - name: reboot
      ansible.windows.win_reboot:
        when: complete.changed