---
- name: Disable ipv6 via registry key
  hosts: all
  gather_facts: no

  tasks:
    win_regedit:
      path: HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
      name: DisabledComponents
      data: 0xff
      type: dword
    register: reg_done
    win_reboot:
      when: reg_done.changed