---

- name: Join windows system into domain_name
  hosts: nondc
  gather_facts: no

  tasks:
    - name: joining to domain
      win_domain_membership:
        dns_domain_name: "demo.lab"
        domain_admin_user: administrator@demo.lab
        domain_admin_password: 'W3lcome$1'
        state: domain
      register: domain_state

      win_reboot:
      when: domain_state.reboot_required