---
- name: install treesize free and google chrome using chocolatey
  hosts: nondc
  become: false
  gather_facts: false
  vars:
    - packages:
      - chocolatey-core.extension
      - chocolatey-windowsupdate.extension
      - treesizefree
      - googlechrome
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: present
