---

- name: define traditional ethernet facts
  hosts: all
  gather_facts: yes

  tasks: 
    - name: debug
      debug:
        msg: "{{ item.connection_name }}"
      with_items:
        - "{{ ansible_facts['interfaces'] }}"