---
- name: Update Windows using Ansible
  hosts: nondc
  
  tasks:
    - name: Win Update
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdate
          - UpdateRollups
        state: installed
        reboot: yes
        log_path: C:\ansible_win_update.txt
